---
- name: Install Docker, Docker Compose, Git, and Clone a Git Repository
  hosts: mezcloud
  remote_user: "{{ ansible_user }}"
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

# Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present
# Install Docker Compose
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
# Start Docker service
    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
# Install Git
    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
# Install Git
    - name: Install Git
      apt:
        name: git
        state: present


    - name: Delete Existing Directory
      file:
        path: /home/houddinii/mezcloud.com
        state: absent
      ignore_errors: yes

    - name: Clone Git Repository to Root Directory
      git:
        repo: "https://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@github.com/mezbauddin/mezcloud.com.git"
        dest: /home/houddinii/mezcloud.com
        version: main
      register: git_clone_result

    - name: Debug Git Clone
      debug:
        var: git_clone_result

#############################################
# # Login to Docker Hub
#     - name: Docker Hub login
#       community.docker.docker_login:
#         username: mezbauddin
#         password: Gonzo198@
#       tags: [docker-login]

# # docker compose.prod up
#     - name: docker compose.prod up
#       command: docker-compose -f /mezbauddin.com-MezCloud/docker-compose.prod.yml up -d
#       args:
#         chdir: /mezbauddin.com-MezCloud
#       tags: [docker-compose.prod-up]
#
#############################################