name: CI/CD for mezbauddin.com

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mezbauddin.com
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  TFE_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  build-push-deploy-provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Terraform Cloud Authentication
        run: |
          # Set up Terraform Cloud authentication
          echo 'credentials "app.terraform.io" {
            token = "${{ env.TFE_TOKEN }}"
          }' > ~/.terraformrc

      - name: Deploy Infrastructure with Terraform
        run: |
          cd infrastructure/terraform
          terraform init
          terraform apply -replace=null_resource.run_ansible -auto-approve

      - name: Run Ansible Deployment
        run: |
          cd infrastructure/ansible/
          ansible-playbook -i inventory.ini install_docker.yml --private-key=/temporary_ke
          # Remove the temporary key after playbook execution
          rm /temporary_key 

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Tag Docker Image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy Application to Server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          # Log in to Docker Hub on the server using docker/login-action
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          # Continue with the deployment
          ssh -o StrictHostKeyChecking=no -i ssh_key -l ${{ env.SERVER_USERNAME }} ${{ env.SERVER_HOST }} '
          cd /home/houddinii/mezbauddin.com-MezCloud && \
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            COMPOSE_FILE=./docker-compose.prod.yml
          else
            COMPOSE_FILE=./docker-compose.staging.yml
          fi && \
          echo "Using Docker Compose file: $COMPOSE_FILE" && \
          docker-compose -f $COMPOSE_FILE down || true
          docker-compose -f $COMPOSE_FILE pull
          docker-compose -f $COMPOSE_FILE up -d
          '
          
